// Code generated by ent, DO NOT EDIT.

package machine

const (
	// Label holds the string label denoting the machine type in the database.
	Label = "machine"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldYear holds the string denoting the year field in the database.
	FieldYear = "year"
	// FieldLiftHeight holds the string denoting the liftheight field in the database.
	FieldLiftHeight = "lift_height"
	// FieldMotorHours holds the string denoting the motorhours field in the database.
	FieldMotorHours = "motor_hours"
	// FieldDrive holds the string denoting the drive field in the database.
	FieldDrive = "drive"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldLoadCapacity holds the string denoting the loadcapacity field in the database.
	FieldLoadCapacity = "load_capacity"
	// FieldRentPrice holds the string denoting the rentprice field in the database.
	FieldRentPrice = "rent_price"
	// FieldSalePrice holds the string denoting the saleprice field in the database.
	FieldSalePrice = "sale_price"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldHidden holds the string denoting the hidden field in the database.
	FieldHidden = "hidden"
	// FieldDeleted holds the string denoting the deleted field in the database.
	FieldDeleted = "deleted"
	// FieldNumberOfImages holds the string denoting the numberofimages field in the database.
	FieldNumberOfImages = "number_of_images"
	// FieldInternalDescription holds the string denoting the internaldescription field in the database.
	FieldInternalDescription = "internal_description"
	// EdgeMachineSpecification holds the string denoting the machinespecification edge name in mutations.
	EdgeMachineSpecification = "machineSpecification"
	// EdgeMachineAccessories holds the string denoting the machineaccessories edge name in mutations.
	EdgeMachineAccessories = "machineAccessories"
	// Table holds the table name of the machine in the database.
	Table = "machines"
	// MachineSpecificationTable is the table that holds the machineSpecification relation/edge.
	MachineSpecificationTable = "machine_specifications"
	// MachineSpecificationInverseTable is the table name for the MachineSpecification entity.
	// It exists in this package in order to avoid circular dependency with the "machinespecification" package.
	MachineSpecificationInverseTable = "machine_specifications"
	// MachineSpecificationColumn is the table column denoting the machineSpecification relation/edge.
	MachineSpecificationColumn = "machine_machine_specification"
	// MachineAccessoriesTable is the table that holds the machineAccessories relation/edge.
	MachineAccessoriesTable = "machine_accessories"
	// MachineAccessoriesInverseTable is the table name for the MachineAccessories entity.
	// It exists in this package in order to avoid circular dependency with the "machineaccessories" package.
	MachineAccessoriesInverseTable = "machine_accessories"
	// MachineAccessoriesColumn is the table column denoting the machineAccessories relation/edge.
	MachineAccessoriesColumn = "machine_machine_accessories"
)

// Columns holds all SQL columns for machine fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldYear,
	FieldLiftHeight,
	FieldMotorHours,
	FieldDrive,
	FieldWeight,
	FieldLoadCapacity,
	FieldRentPrice,
	FieldSalePrice,
	FieldDescription,
	FieldHidden,
	FieldDeleted,
	FieldNumberOfImages,
	FieldInternalDescription,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultHidden holds the default value on creation for the "hidden" field.
	DefaultHidden bool
	// DefaultDeleted holds the default value on creation for the "deleted" field.
	DefaultDeleted bool
	// InternalDescriptionValidator is a validator for the "internalDescription" field. It is called by the builders before save.
	InternalDescriptionValidator func(string) error
)
