// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/machine"
	"api/ent/machinespecification"
	"api/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MachineSpecificationQuery is the builder for querying MachineSpecification entities.
type MachineSpecificationQuery struct {
	config
	limit       *int
	offset      *int
	unique      *bool
	order       []OrderFunc
	fields      []string
	predicates  []predicate.MachineSpecification
	withMachine *MachineQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MachineSpecificationQuery builder.
func (msq *MachineSpecificationQuery) Where(ps ...predicate.MachineSpecification) *MachineSpecificationQuery {
	msq.predicates = append(msq.predicates, ps...)
	return msq
}

// Limit adds a limit step to the query.
func (msq *MachineSpecificationQuery) Limit(limit int) *MachineSpecificationQuery {
	msq.limit = &limit
	return msq
}

// Offset adds an offset step to the query.
func (msq *MachineSpecificationQuery) Offset(offset int) *MachineSpecificationQuery {
	msq.offset = &offset
	return msq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (msq *MachineSpecificationQuery) Unique(unique bool) *MachineSpecificationQuery {
	msq.unique = &unique
	return msq
}

// Order adds an order step to the query.
func (msq *MachineSpecificationQuery) Order(o ...OrderFunc) *MachineSpecificationQuery {
	msq.order = append(msq.order, o...)
	return msq
}

// QueryMachine chains the current query on the "machine" edge.
func (msq *MachineSpecificationQuery) QueryMachine() *MachineQuery {
	query := &MachineQuery{config: msq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := msq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := msq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(machinespecification.Table, machinespecification.FieldID, selector),
			sqlgraph.To(machine.Table, machine.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, machinespecification.MachineTable, machinespecification.MachineColumn),
		)
		fromU = sqlgraph.SetNeighbors(msq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MachineSpecification entity from the query.
// Returns a *NotFoundError when no MachineSpecification was found.
func (msq *MachineSpecificationQuery) First(ctx context.Context) (*MachineSpecification, error) {
	nodes, err := msq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{machinespecification.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (msq *MachineSpecificationQuery) FirstX(ctx context.Context) *MachineSpecification {
	node, err := msq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MachineSpecification ID from the query.
// Returns a *NotFoundError when no MachineSpecification ID was found.
func (msq *MachineSpecificationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{machinespecification.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (msq *MachineSpecificationQuery) FirstIDX(ctx context.Context) int {
	id, err := msq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MachineSpecification entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MachineSpecification entity is found.
// Returns a *NotFoundError when no MachineSpecification entities are found.
func (msq *MachineSpecificationQuery) Only(ctx context.Context) (*MachineSpecification, error) {
	nodes, err := msq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{machinespecification.Label}
	default:
		return nil, &NotSingularError{machinespecification.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (msq *MachineSpecificationQuery) OnlyX(ctx context.Context) *MachineSpecification {
	node, err := msq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MachineSpecification ID in the query.
// Returns a *NotSingularError when more than one MachineSpecification ID is found.
// Returns a *NotFoundError when no entities are found.
func (msq *MachineSpecificationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{machinespecification.Label}
	default:
		err = &NotSingularError{machinespecification.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (msq *MachineSpecificationQuery) OnlyIDX(ctx context.Context) int {
	id, err := msq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MachineSpecifications.
func (msq *MachineSpecificationQuery) All(ctx context.Context) ([]*MachineSpecification, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return msq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (msq *MachineSpecificationQuery) AllX(ctx context.Context) []*MachineSpecification {
	nodes, err := msq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MachineSpecification IDs.
func (msq *MachineSpecificationQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := msq.Select(machinespecification.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (msq *MachineSpecificationQuery) IDsX(ctx context.Context) []int {
	ids, err := msq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (msq *MachineSpecificationQuery) Count(ctx context.Context) (int, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return msq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (msq *MachineSpecificationQuery) CountX(ctx context.Context) int {
	count, err := msq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (msq *MachineSpecificationQuery) Exist(ctx context.Context) (bool, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return msq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (msq *MachineSpecificationQuery) ExistX(ctx context.Context) bool {
	exist, err := msq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MachineSpecificationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (msq *MachineSpecificationQuery) Clone() *MachineSpecificationQuery {
	if msq == nil {
		return nil
	}
	return &MachineSpecificationQuery{
		config:      msq.config,
		limit:       msq.limit,
		offset:      msq.offset,
		order:       append([]OrderFunc{}, msq.order...),
		predicates:  append([]predicate.MachineSpecification{}, msq.predicates...),
		withMachine: msq.withMachine.Clone(),
		// clone intermediate query.
		sql:    msq.sql.Clone(),
		path:   msq.path,
		unique: msq.unique,
	}
}

// WithMachine tells the query-builder to eager-load the nodes that are connected to
// the "machine" edge. The optional arguments are used to configure the query builder of the edge.
func (msq *MachineSpecificationQuery) WithMachine(opts ...func(*MachineQuery)) *MachineSpecificationQuery {
	query := &MachineQuery{config: msq.config}
	for _, opt := range opts {
		opt(query)
	}
	msq.withMachine = query
	return msq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MachineNumber int `json:"machineNumber,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MachineSpecification.Query().
//		GroupBy(machinespecification.FieldMachineNumber).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (msq *MachineSpecificationQuery) GroupBy(field string, fields ...string) *MachineSpecificationGroupBy {
	grbuild := &MachineSpecificationGroupBy{config: msq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := msq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return msq.sqlQuery(ctx), nil
	}
	grbuild.label = machinespecification.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MachineNumber int `json:"machineNumber,omitempty"`
//	}
//
//	client.MachineSpecification.Query().
//		Select(machinespecification.FieldMachineNumber).
//		Scan(ctx, &v)
func (msq *MachineSpecificationQuery) Select(fields ...string) *MachineSpecificationSelect {
	msq.fields = append(msq.fields, fields...)
	selbuild := &MachineSpecificationSelect{MachineSpecificationQuery: msq}
	selbuild.label = machinespecification.Label
	selbuild.flds, selbuild.scan = &msq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a MachineSpecificationSelect configured with the given aggregations.
func (msq *MachineSpecificationQuery) Aggregate(fns ...AggregateFunc) *MachineSpecificationSelect {
	return msq.Select().Aggregate(fns...)
}

func (msq *MachineSpecificationQuery) prepareQuery(ctx context.Context) error {
	for _, f := range msq.fields {
		if !machinespecification.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if msq.path != nil {
		prev, err := msq.path(ctx)
		if err != nil {
			return err
		}
		msq.sql = prev
	}
	return nil
}

func (msq *MachineSpecificationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MachineSpecification, error) {
	var (
		nodes       = []*MachineSpecification{}
		withFKs     = msq.withFKs
		_spec       = msq.querySpec()
		loadedTypes = [1]bool{
			msq.withMachine != nil,
		}
	)
	if msq.withMachine != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, machinespecification.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MachineSpecification).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MachineSpecification{config: msq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, msq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := msq.withMachine; query != nil {
		if err := msq.loadMachine(ctx, query, nodes, nil,
			func(n *MachineSpecification, e *Machine) { n.Edges.Machine = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (msq *MachineSpecificationQuery) loadMachine(ctx context.Context, query *MachineQuery, nodes []*MachineSpecification, init func(*MachineSpecification), assign func(*MachineSpecification, *Machine)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MachineSpecification)
	for i := range nodes {
		if nodes[i].machine_machine_specification == nil {
			continue
		}
		fk := *nodes[i].machine_machine_specification
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(machine.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "machine_machine_specification" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (msq *MachineSpecificationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := msq.querySpec()
	_spec.Node.Columns = msq.fields
	if len(msq.fields) > 0 {
		_spec.Unique = msq.unique != nil && *msq.unique
	}
	return sqlgraph.CountNodes(ctx, msq.driver, _spec)
}

func (msq *MachineSpecificationQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := msq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (msq *MachineSpecificationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   machinespecification.Table,
			Columns: machinespecification.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: machinespecification.FieldID,
			},
		},
		From:   msq.sql,
		Unique: true,
	}
	if unique := msq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := msq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, machinespecification.FieldID)
		for i := range fields {
			if fields[i] != machinespecification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := msq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := msq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := msq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := msq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (msq *MachineSpecificationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(msq.driver.Dialect())
	t1 := builder.Table(machinespecification.Table)
	columns := msq.fields
	if len(columns) == 0 {
		columns = machinespecification.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if msq.sql != nil {
		selector = msq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if msq.unique != nil && *msq.unique {
		selector.Distinct()
	}
	for _, p := range msq.predicates {
		p(selector)
	}
	for _, p := range msq.order {
		p(selector)
	}
	if offset := msq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := msq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MachineSpecificationGroupBy is the group-by builder for MachineSpecification entities.
type MachineSpecificationGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (msgb *MachineSpecificationGroupBy) Aggregate(fns ...AggregateFunc) *MachineSpecificationGroupBy {
	msgb.fns = append(msgb.fns, fns...)
	return msgb
}

// Scan applies the group-by query and scans the result into the given value.
func (msgb *MachineSpecificationGroupBy) Scan(ctx context.Context, v any) error {
	query, err := msgb.path(ctx)
	if err != nil {
		return err
	}
	msgb.sql = query
	return msgb.sqlScan(ctx, v)
}

func (msgb *MachineSpecificationGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range msgb.fields {
		if !machinespecification.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := msgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := msgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (msgb *MachineSpecificationGroupBy) sqlQuery() *sql.Selector {
	selector := msgb.sql.Select()
	aggregation := make([]string, 0, len(msgb.fns))
	for _, fn := range msgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(msgb.fields)+len(msgb.fns))
		for _, f := range msgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(msgb.fields...)...)
}

// MachineSpecificationSelect is the builder for selecting fields of MachineSpecification entities.
type MachineSpecificationSelect struct {
	*MachineSpecificationQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mss *MachineSpecificationSelect) Aggregate(fns ...AggregateFunc) *MachineSpecificationSelect {
	mss.fns = append(mss.fns, fns...)
	return mss
}

// Scan applies the selector query and scans the result into the given value.
func (mss *MachineSpecificationSelect) Scan(ctx context.Context, v any) error {
	if err := mss.prepareQuery(ctx); err != nil {
		return err
	}
	mss.sql = mss.MachineSpecificationQuery.sqlQuery(ctx)
	return mss.sqlScan(ctx, v)
}

func (mss *MachineSpecificationSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(mss.fns))
	for _, fn := range mss.fns {
		aggregation = append(aggregation, fn(mss.sql))
	}
	switch n := len(*mss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		mss.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		mss.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := mss.sql.Query()
	if err := mss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
