// Code generated by ent, DO NOT EDIT.

package machineaccessories

const (
	// Label holds the string label denoting the machineaccessories type in the database.
	Label = "machine_accessories"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName1 holds the string denoting the name1 field in the database.
	FieldName1 = "name1"
	// FieldName2 holds the string denoting the name2 field in the database.
	FieldName2 = "name2"
	// FieldName3 holds the string denoting the name3 field in the database.
	FieldName3 = "name3"
	// FieldName4 holds the string denoting the name4 field in the database.
	FieldName4 = "name4"
	// FieldName5 holds the string denoting the name5 field in the database.
	FieldName5 = "name5"
	// FieldName6 holds the string denoting the name6 field in the database.
	FieldName6 = "name6"
	// FieldName7 holds the string denoting the name7 field in the database.
	FieldName7 = "name7"
	// FieldName8 holds the string denoting the name8 field in the database.
	FieldName8 = "name8"
	// FieldName9 holds the string denoting the name9 field in the database.
	FieldName9 = "name9"
	// FieldName10 holds the string denoting the name10 field in the database.
	FieldName10 = "name10"
	// EdgeMachine holds the string denoting the machine edge name in mutations.
	EdgeMachine = "machine"
	// Table holds the table name of the machineaccessories in the database.
	Table = "machine_accessories"
	// MachineTable is the table that holds the machine relation/edge.
	MachineTable = "machine_accessories"
	// MachineInverseTable is the table name for the Machine entity.
	// It exists in this package in order to avoid circular dependency with the "machine" package.
	MachineInverseTable = "machines"
	// MachineColumn is the table column denoting the machine relation/edge.
	MachineColumn = "machine_machine_accessories"
)

// Columns holds all SQL columns for machineaccessories fields.
var Columns = []string{
	FieldID,
	FieldName1,
	FieldName2,
	FieldName3,
	FieldName4,
	FieldName5,
	FieldName6,
	FieldName7,
	FieldName8,
	FieldName9,
	FieldName10,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "machine_accessories"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"machine_machine_accessories",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
